-- Execute no SQL Editor do Supabase.
-- A tabela auth.users é criada e administrada pelo Supabase Auth.

create table if not exists public.perfis (
    id uuid primary key references auth.users(id) on delete cascade,
    email text not null,
    criado_em timestamptz not null default timezone('utc', now())
);

alter table public.perfis enable row level security;

drop policy if exists "Usuários podem visualizar seu perfil" on public.perfis;
create policy "Usuários podem visualizar seu perfil"
    on public.perfis
    for select
    to authenticated
    using (id = auth.uid());

drop policy if exists "Usuários podem atualizar seu perfil" on public.perfis;
create policy "Usuários podem atualizar seu perfil"
    on public.perfis
    for update
    to authenticated
    using (id = auth.uid())
    with check (id = auth.uid());

create or replace function public.criar_perfil_usuario()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
    insert into public.perfis (id, email)
    values (new.id, new.email)
    on conflict (id) do update set email = excluded.email;
    return new;
end;
$$;

drop trigger if exists criar_perfil_apos_cadastro on auth.users;
create trigger criar_perfil_apos_cadastro
    after insert on auth.users
    for each row execute function public.criar_perfil_usuario();

create table if not exists public.clientes (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    nome text not null,
    telefone text,
    criado_em timestamptz not null default timezone('utc', now()),
    unique (user_id, nome, telefone)
);

create index if not exists clientes_user_id_idx
    on public.clientes(user_id);

alter table public.clientes enable row level security;

drop policy if exists "Usuários podem visualizar seus clientes" on public.clientes;
create policy "Usuários podem visualizar seus clientes"
    on public.clientes
    for select
    to authenticated
    using (user_id = auth.uid());

drop policy if exists "Usuários podem criar seus clientes" on public.clientes;
create policy "Usuários podem criar seus clientes"
    on public.clientes
    for insert
    to authenticated
    with check (user_id = auth.uid());

drop policy if exists "Usuários podem atualizar seus clientes" on public.clientes;
create policy "Usuários podem atualizar seus clientes"
    on public.clientes
    for update
    to authenticated
    using (user_id = auth.uid())
    with check (user_id = auth.uid());

drop policy if exists "Usuários podem excluir seus clientes" on public.clientes;
create policy "Usuários podem excluir seus clientes"
    on public.clientes
    for delete
    to authenticated
    using (user_id = auth.uid());

create table if not exists public.pedidos (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade,
    cliente text not null,
    telefone text,
    setor text not null,
    servico text not null,
    valor numeric(12, 2) not null check (valor >= 0),
    data_pedido text not null,
    status text not null default 'Pendente' check (status in ('Pendente', 'Em produção', 'Confirmado', 'Cancelado')),
    observacoes text,
    criado_em timestamptz not null default timezone('utc', now())
);

-- Pedidos criados antes do isolamento por usuário ficam sem autor até serem associados.

alter table public.pedidos
    add column if not exists user_id uuid references auth.users(id);

create index if not exists pedidos_user_id_idx
    on public.pedidos(user_id);

alter table public.pedidos enable row level security;

drop policy if exists "Usuários podem visualizar seus pedidos" on public.pedidos;
create policy "Usuários podem visualizar seus pedidos"
    on public.pedidos
    for select
    to authenticated
    using (user_id = auth.uid());

drop policy if exists "Usuários podem criar seus pedidos" on public.pedidos;
create policy "Usuários podem criar seus pedidos"
    on public.pedidos
    for insert
    to authenticated
    with check (user_id = auth.uid());

drop policy if exists "Usuários podem atualizar seus pedidos" on public.pedidos;
create policy "Usuários podem atualizar seus pedidos"
    on public.pedidos
    for update
    to authenticated
    using (user_id = auth.uid())
    with check (user_id = auth.uid());

drop policy if exists "Usuários podem excluir seus pedidos" on public.pedidos;
create policy "Usuários podem excluir seus pedidos"
    on public.pedidos
    for delete
    to authenticated
    using (user_id = auth.uid());
